// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABd2jrO4cilsFt43ThmganCVxkMu3Qyy8',
    appId: '1:473416146571:web:630f86db9631f603a63e8e',
    messagingSenderId: '473416146571',
    projectId: 'flutter-auth-app-a3af7',
    authDomain: 'flutter-auth-app-a3af7.firebaseapp.com',
    storageBucket: 'flutter-auth-app-a3af7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu7DprEfL3GcXC9DyvDFB4kHYyd1p46pc',
    appId: '1:473416146571:android:5a66404731184e67a63e8e',
    messagingSenderId: '473416146571',
    projectId: 'flutter-auth-app-a3af7',
    storageBucket: 'flutter-auth-app-a3af7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdGvdEADuZ3MCDyHSWglNrrHq67z-4Sho',
    appId: '1:473416146571:ios:b12f14bc5ca48015a63e8e',
    messagingSenderId: '473416146571',
    projectId: 'flutter-auth-app-a3af7',
    storageBucket: 'flutter-auth-app-a3af7.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdGvdEADuZ3MCDyHSWglNrrHq67z-4Sho',
    appId: '1:473416146571:ios:b12f14bc5ca48015a63e8e',
    messagingSenderId: '473416146571',
    projectId: 'flutter-auth-app-a3af7',
    storageBucket: 'flutter-auth-app-a3af7.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABd2jrO4cilsFt43ThmganCVxkMu3Qyy8',
    appId: '1:473416146571:web:73fbcfe0d173815ba63e8e',
    messagingSenderId: '473416146571',
    projectId: 'flutter-auth-app-a3af7',
    authDomain: 'flutter-auth-app-a3af7.firebaseapp.com',
    storageBucket: 'flutter-auth-app-a3af7.firebasestorage.app',
  );
}
